[tool.cibuildwheel]
build-frontend = "build"
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"

skip = [
  "*-manylinux_i686",
  "*-musllinux_i686",
  "*-win32",
  "pp*",
]

macos.archs = ["x86_64", "arm64"]
test-skip = "*-macosx_arm64"
build-verbosity = 1

linux.before-all = "yum install -y llvm-toolset-7.0 || yum -v install -y llvm-toolset-7.0"
before-test = "pip install -r test-requirements.txt"
test-command = "pytest {project}/tests"

[tool.cibuildwheel.environment]
MYPYC_OPT_LEVEL = "3"
MYPYC_DEBUG_LEVEL = "0"

[tool.cibuildwheel.windows.environment]
MYPYC_OPT_LEVEL = "2"
MYPYC_DEBUG_LEVEL = "0"

[tool.cibuildwheel.linux.environment]
MYPYC_OPT_LEVEL = "3"
MYPYC_DEBUG_LEVEL = "0"
PATH = "$PATH:/opt/rh/llvm-toolset-7.0/root/usr/bin"
LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:/opt/rh/llvm-toolset-7.0/root/usr/lib64"
CC = "clang"

[[tool.cibuildwheel.overrides]]
select = "*musllinux*"
before-all = "apk add --no-cache clang"
before-test = "pip install -r test-requirements.txt"
environment = { MYPYC_OPT_LEVEL="3", MYPYC_DEBUG_LEVEL="0", CC="clang" }